spring:
  ai:
    mcp:
      client:
        stdio:
          servers:
            amap-map-server:
              command: "npx"      # ✅ Linux 只能用 npx
              args:
                - "-y"
                - "@amap/amap-maps-mcp-server"

# 生产环境通常建议关闭 Swagger 以提高安全性（可选）
swagger:
  enable: false

# 生产环境日志级别可以调高（可选）
logging:
  level:
    com.microservice.skeleton.user.mapper: INFO
